//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESMS.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string controller {
            get {
                return ResourceManager.GetString("controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string emailAdresa {
            get {
                return ResourceManager.GetString("emailAdresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri menus.
        /// </summary>
        public static string emriMenus {
            get {
                return ResourceManager.GetString("emriMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri menus anglisht.
        /// </summary>
        public static string emriMenusAnglisht {
            get {
                return ResourceManager.GetString("emriMenusAnglisht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri menus shqip.
        /// </summary>
        public static string emriMenusShqip {
            get {
                return ResourceManager.GetString("emriMenusShqip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi.
        /// </summary>
        public static string fjalekalimi {
            get {
                return ResourceManager.GetString("fjalekalimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshije.
        /// </summary>
        public static string fshije {
            get {
                return ResourceManager.GetString("fshije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikona.
        /// </summary>
        public static string ikona {
            get {
                return ResourceManager.GetString("ikona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keni harruar fjalëkalimin?.
        /// </summary>
        public static string keniHarruarFjalekalimin {
            get {
                return ResourceManager.GetString("keniHarruarFjalekalimin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyqu.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdorni llogarinë për tu kyqur..
        /// </summary>
        public static string loginText {
            get {
                return ResourceManager.GetString("loginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Më kujto?.
        /// </summary>
        public static string meKujto {
            get {
                return ResourceManager.GetString("meKujto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metoda.
        /// </summary>
        public static string metoda {
            get {
                return ResourceManager.GetString("metoda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho.
        /// </summary>
        public static string ndrysho {
            get {
                return ResourceManager.GetString("ndrysho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regjistro nën-menu.
        /// </summary>
        public static string regjistroNenMenu {
            get {
                return ResourceManager.GetString("regjistroNenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veprimet.
        /// </summary>
        public static string veprimet {
            get {
                return ResourceManager.GetString("veprimet", resourceCulture);
            }
        }
    }
}
