//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESMS.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju nuk jeni i autorizuar te qaseni kete faqe..
        /// </summary>
        public static string accessDenied {
            get {
                return ResourceManager.GetString("accessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qasje e pa autorizuar.
        /// </summary>
        public static string accessDeniedTitle {
            get {
                return ResourceManager.GetString("accessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjo llogari është bllokuar, ju lutem provoni përsëri më vonë..
        /// </summary>
        public static string accountLockout {
            get {
                return ResourceManager.GetString("accountLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogari e bllokuar.
        /// </summary>
        public static string accountLockoutTitle {
            get {
                return ResourceManager.GetString("accountLockoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string adresa {
            get {
                return ResourceManager.GetString("adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa 2(opsionale).
        /// </summary>
        public static string adresaOpsionale {
            get {
                return ResourceManager.GetString("adresaOpsionale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string aktiv {
            get {
                return ResourceManager.GetString("aktiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitetet e fundit në sistem.
        /// </summary>
        public static string aktivitetNeSistem {
            get {
                return ResourceManager.GetString("aktivitetNeSistem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dhe.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulimi i 2FA nuk i ndryshon çelësat që përdoren në applikacionin për autentifikim. Nëse dëshironi ti ndryshoni çelësat që përdoren në aplikacionin për autentifikim ju duhet të.
        /// </summary>
        public static string anulimi2FADescription {
            get {
                return ResourceManager.GetString("anulimi2FADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resetoni çelësat për autentifikim..
        /// </summary>
        public static string anulimi2FAReset {
            get {
                return ResourceManager.GetString("anulimi2FAReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulo 2FA.
        /// </summary>
        public static string anulo2FA {
            get {
                return ResourceManager.GetString("anulo2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulo autentifikimin 2-hapësh.
        /// </summary>
        public static string anuloTOTP {
            get {
                return ResourceManager.GetString("anuloTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngarko dokumentin (opsional).
        /// </summary>
        public static string attachDocument {
            get {
                return ResourceManager.GetString("attachDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria juaj mbrohet me aplikacionin për autentifikim. Shtypni kodin e autentifikatorit më poshtë..
        /// </summary>
        public static string autentifikatorTitle {
            get {
                return ResourceManager.GetString("autentifikatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentifikimi dy hapësh.
        /// </summary>
        public static string autentifikimi2Hapesh {
            get {
                return ResourceManager.GetString("autentifikimi2Hapesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentifikimi dy-hapësh (2FA).
        /// </summary>
        public static string autentifikimiDyHapesh {
            get {
                return ResourceManager.GetString("autentifikimiDyHapesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi për autentifikim.
        /// </summary>
        public static string authenticatorCode {
            get {
                return ResourceManager.GetString("authenticatorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballina.
        /// </summary>
        public static string ballina {
            get {
                return ResourceManager.GetString("ballina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string claim {
            get {
                return ResourceManager.GetString("claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim vlera.
        /// </summary>
        public static string claimValue {
            get {
                return ResourceManager.GetString("claimValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to klikoni këtu për tu kyqur.
        /// </summary>
        public static string clickHereToLogIn {
            get {
                return ResourceManager.GetString("clickHereToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi dhe fjalëkalimi konfirmuar nuk përputhen..
        /// </summary>
        public static string comparePasswordError {
            get {
                return ResourceManager.GetString("comparePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faleminderit për konfirmim të ndryshimit të email adresës..
        /// </summary>
        public static string confirmEmailChange {
            get {
                return ResourceManager.GetString("confirmEmailChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmimi i ndryshimit të email adresës.
        /// </summary>
        public static string confirmEmailChangeTitle {
            get {
                return ResourceManager.GetString("confirmEmailChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolleri.
        /// </summary>
        public static string controller {
            get {
                return ResourceManager.GetString("controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data punësimit deri.
        /// </summary>
        public static string dataPunesimitDeri {
            get {
                return ResourceManager.GetString("dataPunesimitDeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dërgo.
        /// </summary>
        public static string dergo {
            get {
                return ResourceManager.GetString("dergo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dërgo email adresën për verifikim.
        /// </summary>
        public static string dergoEmailPerVerifikim {
            get {
                return ResourceManager.GetString("dergoEmailPerVerifikim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detajet.
        /// </summary>
        public static string detajet {
            get {
                return ResourceManager.GetString("detajet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dita e fillimit të punës.
        /// </summary>
        public static string ditaPunesimit {
            get {
                return ResourceManager.GetString("ditaPunesimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditëlindja.
        /// </summary>
        public static string ditelindja {
            get {
                return ResourceManager.GetString("ditelindja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokument.
        /// </summary>
        public static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk keni qasje në pajisjen për autentifikim? Ju mundeni .
        /// </summary>
        public static string donotHaveAccessTOTP {
            get {
                return ResourceManager.GetString("donotHaveAccessTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fillimit te punes.
        /// </summary>
        public static string dtEmployment {
            get {
                return ResourceManager.GetString("dtEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data insertimit.
        /// </summary>
        public static string dtInsertimit {
            get {
                return ResourceManager.GetString("dtInsertimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string emailAdresa {
            get {
                return ResourceManager.GetString("emailAdresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa është konfirmuar me sukses..
        /// </summary>
        public static string emailAdresaKonfirmuar {
            get {
                return ResourceManager.GetString("emailAdresaKonfirmuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa re.
        /// </summary>
        public static string emailAdresaRe {
            get {
                return ResourceManager.GetString("emailAdresaRe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmimi i email adresës.
        /// </summary>
        public static string emailConfirmationTitle {
            get {
                return ResourceManager.GetString("emailConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imella për verifikim është dërguar. Ju lutem shikoni imellën..
        /// </summary>
        public static string emailVerificationSend {
            get {
                return ResourceManager.GetString("emailVerificationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fillimit te punes.
        /// </summary>
        public static string employmentDate {
            get {
                return ResourceManager.GetString("employmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        public static string emri {
            get {
                return ResourceManager.GetString("emri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri kompjuterit.
        /// </summary>
        public static string emriKompjuterit {
            get {
                return ResourceManager.GetString("emriKompjuterit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri menus.
        /// </summary>
        public static string emriMenus {
            get {
                return ResourceManager.GetString("emriMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri menus anglisht.
        /// </summary>
        public static string emriMenusAnglisht {
            get {
                return ResourceManager.GetString("emriMenusAnglisht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri menus shqip.
        /// </summary>
        public static string emriMenusShqip {
            get {
                return ResourceManager.GetString("emriMenusShqip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri mesëm.
        /// </summary>
        public static string emriMesem {
            get {
                return ResourceManager.GetString("emriMesem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri nen-menus anglisht.
        /// </summary>
        public static string emriNenMenusEN {
            get {
                return ResourceManager.GetString("emriNenMenusEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri nen-menus shqip.
        /// </summary>
        public static string emriNenMenusSQ {
            get {
                return ResourceManager.GetString("emriNenMenusSQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dita e kthimit në punë.
        /// </summary>
        public static string endDateLeave {
            get {
                return ResourceManager.GetString("endDateLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shtypni email adresën..
        /// </summary>
        public static string enterEmail {
            get {
                return ResourceManager.GetString("enterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekzekuto pagat.
        /// </summary>
        public static string executeSalaries {
            get {
                return ResourceManager.GetString("executeSalaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguroni aplikacionin për autentifikim.
        /// </summary>
        public static string FA2KonfiguroniAplikacionin {
            get {
                return ResourceManager.GetString("FA2KonfiguroniAplikacionin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femër.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femër.
        /// </summary>
        public static string femer {
            get {
                return ResourceManager.GetString("femer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plotëso.
        /// </summary>
        public static string fillIn {
            get {
                return ResourceManager.GetString("fillIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi.
        /// </summary>
        public static string fjalekalimi {
            get {
                return ResourceManager.GetString("fjalekalimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi aktual.
        /// </summary>
        public static string fjalekalimiAktual {
            get {
                return ResourceManager.GetString("fjalekalimiAktual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri dhe fjalëkalimi konfirmues nuk përputhet..
        /// </summary>
        public static string fjalekalimiNukPerputhet {
            get {
                return ResourceManager.GetString("fjalekalimiNukPerputhet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi ri.
        /// </summary>
        public static string fjalekalimiRi {
            get {
                return ResourceManager.GetString("fjalekalimiRi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi juaj është vendosur..
        /// </summary>
        public static string fjalekalimiVendosur {
            get {
                return ResourceManager.GetString("fjalekalimiVendosur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keni harruar fjalëkalimin?.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmimi i rikthimit të fjalëkalimit.
        /// </summary>
        public static string forgotPasswordConfir {
            get {
                return ResourceManager.GetString("forgotPasswordConfir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju lutem shikoni imellën për të rikthyer fjalëkalimin..
        /// </summary>
        public static string forgotPasswordTitle {
            get {
                return ResourceManager.GetString("forgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formati i numrit nuk eshte valid.
        /// </summary>
        public static string formatiNrTelGabim {
            get {
                return ResourceManager.GetString("formatiNrTelGabim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotografia profilit.
        /// </summary>
        public static string fotoProfilit {
            get {
                return ResourceManager.GetString("fotoProfilit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshije.
        /// </summary>
        public static string fshije {
            get {
                return ResourceManager.GetString("fshije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjo fushë është obligative.
        /// </summary>
        public static string fusheObligative {
            get {
                return ResourceManager.GetString("fusheObligative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabim gjatë ndryshimit të email adresës..
        /// </summary>
        public static string gabimNdryshimiEmail {
            get {
                return ResourceManager.GetString("gabimNdryshimiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabim gjatë ndryshimit të emrit të përdoruesit.
        /// </summary>
        public static string gabimNdryshimiusername {
            get {
                return ResourceManager.GetString("gabimNdryshimiusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} duhet të jetë minimum {2} dhe maksimum {1} karaktere i gjatë..
        /// </summary>
        public static string gjatesiaFjalekalimit {
            get {
                return ResourceManager.GetString("gjatesiaFjalekalimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjenerimi i kodeve për rivendose me 2FA.
        /// </summary>
        public static string gjenerimiKodeve2FA {
            get {
                return ResourceManager.GetString("gjenerimiKodeve2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjenerimi i kodeve të reja për rikthim nuk ndryshon çelësat që përdoren në aplikacionet për autentifikim. Nëse dëshironi të ndryshoni çelësin që përdoret në aplikacionin për autentifikim ju duhet .
        /// </summary>
        public static string gjenerimiKoditTeRiPerApp {
            get {
                return ResourceManager.GetString("gjenerimiKoditTeRiPerApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjenero kodet për rivendosje.
        /// </summary>
        public static string gjeneroKodetPerRivendosje {
            get {
                return ResourceManager.GetString("gjeneroKodetPerRivendosje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjinia.
        /// </summary>
        public static string gjinia {
            get {
                return ResourceManager.GetString("gjinia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupi.
        /// </summary>
        public static string grupi {
            get {
                return ResourceManager.GetString("grupi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harrojeni këtë shfletues.
        /// </summary>
        public static string harrojeniShfletuesin {
            get {
                return ResourceManager.GetString("harrojeniShfletuesin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historiku i pagave të egzekutuara.
        /// </summary>
        public static string historikuPagave {
            get {
                return ResourceManager.GetString("historikuPagave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN kodi.
        /// </summary>
        public static string ibanKode {
            get {
                return ResourceManager.GetString("ibanKode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iban-i nuk është valid..
        /// </summary>
        public static string ibanValidation {
            get {
                return ResourceManager.GetString("ibanValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikona.
        /// </summary>
        public static string ikona {
            get {
                return ResourceManager.GetString("ikona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi nuk është i saktë..
        /// </summary>
        public static string invalidCodeTOTP {
            get {
                return ResourceManager.GetString("invalidCodeTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat nuk janë valide!.
        /// </summary>
        public static string invalidData {
            get {
                return ResourceManager.GetString("invalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju duhet.
        /// </summary>
        public static string juDuhet {
            get {
                return ResourceManager.GetString("juDuhet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju keni.
        /// </summary>
        public static string juKeni {
            get {
                return ResourceManager.GetString("juKeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju mundeni.
        /// </summary>
        public static string juMundeni {
            get {
                return ResourceManager.GetString("juMundeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keni harruar fjalëkalimin?.
        /// </summary>
        public static string keniHarruarFjalekalimin {
            get {
                return ResourceManager.GetString("keniHarruarFjalekalimin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërko.
        /// </summary>
        public static string kerko {
            get {
                return ResourceManager.GetString("kerko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kode të mbetura.
        /// </summary>
        public static string kodeTeMbetura {
            get {
                return ResourceManager.GetString("kodeTeMbetura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to të gjeneroni një bashkësi të re të kodeve.
        /// </summary>
        public static string kodeTeReja {
            get {
                return ResourceManager.GetString("kodeTeReja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kodet e mbetura..
        /// </summary>
        public static string kodetMbetura {
            get {
                return ResourceManager.GetString("kodetMbetura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodet për kthim.
        /// </summary>
        public static string kodetPerKthim {
            get {
                return ResourceManager.GetString("kodetPerKthim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi për verifikim.
        /// </summary>
        public static string kodiPerVerifikim {
            get {
                return ResourceManager.GetString("kodiPerVerifikim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi postal.
        /// </summary>
        public static string kodiPostal {
            get {
                return ResourceManager.GetString("kodiPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguro aplikacionin për autentifikim.
        /// </summary>
        public static string konfiguroApp2FA {
            get {
                return ResourceManager.GetString("konfiguroApp2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo fjalëkalimin.
        /// </summary>
        public static string konfirmoFjalekalimin {
            get {
                return ResourceManager.GetString("konfirmoFjalekalimin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrata punës.
        /// </summary>
        public static string kontrataPunes {
            get {
                return ResourceManager.GetString("kontrataPunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolloni formatin e email adresës.
        /// </summary>
        public static string kontrolloFormatinEmail {
            get {
                return ResourceManager.GetString("kontrolloFormatinEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolloni formatin e kodit postar.
        /// </summary>
        public static string kontrolloFormatinKodiPostar {
            get {
                return ResourceManager.GetString("kontrolloFormatinKodiPostar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolloni formatin e telefonit.
        /// </summary>
        public static string kontrolloFormatinTelefonit {
            get {
                return ResourceManager.GetString("kontrolloFormatinTelefonit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjuha.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arsyeja pushimit.
        /// </summary>
        public static string leaveReason {
            get {
                return ResourceManager.GetString("leaveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regjistrimi i kërkesës për pushim.
        /// </summary>
        public static string LeaveRequest {
            get {
                return ResourceManager.GetString("LeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e punëtorve të regjistruar.
        /// </summary>
        public static string listaPunetorve {
            get {
                return ResourceManager.GetString("listaPunetorve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista kërkesave për pushim.
        /// </summary>
        public static string listOfLeaves {
            get {
                return ResourceManager.GetString("listOfLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyqu.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri përdoruesit ose fjalëkalimi nuk është në rregull..
        /// </summary>
        public static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kyqeni me kodet për rikthim.
        /// </summary>
        public static string loginRecoveryCodes {
            get {
                return ResourceManager.GetString("loginRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdorni llogarinë për tu kyqur..
        /// </summary>
        public static string loginText {
            get {
                return ResourceManager.GetString("loginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeni q&apos;kyqur me sukses..
        /// </summary>
        public static string logOutSuccess {
            get {
                return ResourceManager.GetString("logOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q&apos;kyqja me sukses!.
        /// </summary>
        public static string logOutSuccessTitle {
            get {
                return ResourceManager.GetString("logOutSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nëse e humbni pajisjen dhe nuk keni kodet për rikthim ju do të humbni çasjen në llogari..
        /// </summary>
        public static string loseRecoveryCodes {
            get {
                return ResourceManager.GetString("loseRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mashkull.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mashkull.
        /// </summary>
        public static string mashkull {
            get {
                return ResourceManager.GetString("mashkull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbiemri.
        /// </summary>
        public static string mbiemri {
            get {
                return ResourceManager.GetString("mbiemri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbylle.
        /// </summary>
        public static string mbylle {
            get {
                return ResourceManager.GetString("mbylle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Më kujto?.
        /// </summary>
        public static string meKujto {
            get {
                return ResourceManager.GetString("meKujto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menaxhimi i Email adresës.
        /// </summary>
        public static string menaxhimiEmail {
            get {
                return ResourceManager.GetString("menaxhimiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menaxhoni llogarinë tuaj.
        /// </summary>
        public static string menaxhoniLlogarine {
            get {
                return ResourceManager.GetString("menaxhoniLlogarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metoda.
        /// </summary>
        public static string metoda {
            get {
                return ResourceManager.GetString("metoda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa për verifikim është dërguar. Ju lutem shikoni email adresën për verifikim..
        /// </summary>
        public static string msgEmailAdresa {
            get {
                return ResourceManager.GetString("msgEmailAdresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka ndodhur një gabim gjatë ruajtjes..
        /// </summary>
        public static string msgGabimRuajtja {
            get {
                return ResourceManager.GetString("msgGabimRuajtja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat janë ruajtur me sukses..
        /// </summary>
        public static string msgRuajtjaSukses {
            get {
                return ResourceManager.GetString("msgRuajtjaSukses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muaji.
        /// </summary>
        public static string muaji {
            get {
                return ResourceManager.GetString("muaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndryshimi i të dhënave.
        /// </summary>
        public static string ndryshimTeDhenave {
            get {
                return ResourceManager.GetString("ndryshimTeDhenave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho.
        /// </summary>
        public static string ndrysho {
            get {
                return ResourceManager.GetString("ndrysho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho email adresën.
        /// </summary>
        public static string ndryshoEmailAdresen {
            get {
                return ResourceManager.GetString("ndryshoEmailAdresen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndryshoni të dhënat e llogarisë.
        /// </summary>
        public static string ndryshoniTeDhenatLlogarise {
            get {
                return ResourceManager.GetString("ndryshoniTeDhenatLlogarise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to në aplikacionin për autentifikim dy hapësh. Hapsirat dhe lidhëset nuk kanë rëndësi..
        /// </summary>
        public static string neAplikacionin2FA {
            get {
                return ResourceManager.GetString("neAplikacionin2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngarko fotografinë.
        /// </summary>
        public static string ngarkoFotografine {
            get {
                return ResourceManager.GetString("ngarkoFotografine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngarko kontraten.
        /// </summary>
        public static string ngarkoKontraten {
            get {
                return ResourceManager.GetString("ngarkoKontraten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju keni një kod të mbetur..
        /// </summary>
        public static string njeKodMbetur {
            get {
                return ResourceManager.GetString("njeKodMbetur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munde te shtypi 1 deri 100 karektere.
        /// </summary>
        public static string nrKaraktereve {
            get {
                return ResourceManager.GetString("nrKaraktereve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri telefonit.
        /// </summary>
        public static string nrTel {
            get {
                return ResourceManager.GetString("nrTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju nuk keni të krijuar një llogari në këtë aplikacion. Krijoni një llogari ashtu që të mund të kyqeni pa çasje të jashtme..
        /// </summary>
        public static string nukKaLlogari {
            get {
                return ResourceManager.GetString("nukKaLlogari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju nuk keni asnjë kod të gjeneruar..
        /// </summary>
        public static string nukKaRecoveryCodes {
            get {
                return ResourceManager.GetString("nukKaRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri i përdoruesve të regjistruar.
        /// </summary>
        public static string numriPerdoruesve {
            get {
                return ResourceManager.GetString("numriPerdoruesve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri personal.
        /// </summary>
        public static string numriPersonal {
            get {
                return ResourceManager.GetString("numriPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ose.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paga.
        /// </summary>
        public static string paga {
            get {
                return ResourceManager.GetString("paga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to para se të kyqeni me këto kode..
        /// </summary>
        public static string paraSeTekyqeni {
            get {
                return ResourceManager.GetString("paraSeTekyqeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasiv.
        /// </summary>
        public static string pasiv {
            get {
                return ResourceManager.GetString("pasiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to për.
        /// </summary>
        public static string per {
            get {
                return ResourceManager.GetString("per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përditësimi fjalëkalimit.
        /// </summary>
        public static string perditesimiFjalekalimit {
            get {
                return ResourceManager.GetString("perditesimiFjalekalimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te dhenat jane perditesuar me sukses!.
        /// </summary>
        public static string perditesimiMeSukses {
            get {
                return ResourceManager.GetString("perditesimiMeSukses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përditëso fjalëkalimin.
        /// </summary>
        public static string perditesoFjalekalimi {
            get {
                return ResourceManager.GetString("perditesoFjalekalimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Për të përdorur aplikacionin për autentifikim duhet të ndjekni hapat vijues:.
        /// </summary>
        public static string perdorimiIAplikacioninPerAutentifikim {
            get {
                return ResourceManager.GetString("perdorimiIAplikacioninPerAutentifikim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesi.
        /// </summary>
        public static string perdoruesi {
            get {
                return ResourceManager.GetString("perdoruesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përshkrimi.
        /// </summary>
        public static string pershkrimi {
            get {
                return ResourceManager.GetString("pershkrimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pershkrimi pozitës.
        /// </summary>
        public static string pershkrimiPozites {
            get {
                return ResourceManager.GetString("pershkrimiPozites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat personale.
        /// </summary>
        public static string personalData {
            get {
                return ResourceManager.GetString("personalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rregulla.
        /// </summary>
        public static string policy {
            get {
                return ResourceManager.GetString("policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozita e punës.
        /// </summary>
        public static string pozitaPunes {
            get {
                return ResourceManager.GetString("pozitaPunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ky proces anulon 2FA derisa ju të konfiguroni aplikacionin për autenfikim. Nëse nuk kompletoni konfigurimin e aplikacionit për autenfikim ju mund të humbni çasjen në llogarinë tuaj..
        /// </summary>
        public static string procesi2FA {
            get {
                return ResourceManager.GetString("procesi2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili.
        /// </summary>
        public static string profili {
            get {
                return ResourceManager.GetString("profili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qyteti.
        /// </summary>
        public static string qyteti {
            get {
                return ResourceManager.GetString("qyteti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regjistrimi nën menysë.
        /// </summary>
        public static string regjistrimiNenMenu {
            get {
                return ResourceManager.GetString("regjistrimiNenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regjistro nën-menu.
        /// </summary>
        public static string regjistroNenMenu {
            get {
                return ResourceManager.GetString("regjistroNenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbaj mend këtë kompjuter.
        /// </summary>
        public static string rememberMachine {
            get {
                return ResourceManager.GetString("rememberMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lloji raportit.
        /// </summary>
        public static string reportType {
            get {
                return ResourceManager.GetString("reportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rikthe.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivendos çelësat për autentifikim.
        /// </summary>
        public static string resetAuthenticatorKey {
            get {
                return ResourceManager.GetString("resetAuthenticatorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rikthimi fjalëkalimit tuaj..
        /// </summary>
        public static string resetPasswordBody {
            get {
                return ResourceManager.GetString("resetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi është resetuar. Ju lutem .
        /// </summary>
        public static string resetPasswordSuccess {
            get {
                return ResourceManager.GetString("resetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rikthimi fjalëkalimit.
        /// </summary>
        public static string resetPasswordTitle {
            get {
                return ResourceManager.GetString("resetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rikthimi fjalekalimit.
        /// </summary>
        public static string resetPasswordTitleEmail {
            get {
                return ResourceManager.GetString("resetPasswordTitleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nëse i rivendosni çelësat për autentifikim, aplikacioni për autentifkim nuk do të punoj përderisa ju nuk e rikonfikuroni atë..
        /// </summary>
        public static string resetRecoverCodesMessage {
            get {
                return ResourceManager.GetString("resetRecoverCodesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shqyrto.
        /// </summary>
        public static string review {
            get {
                return ResourceManager.GetString("review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivendos aplikacionin për autentifikim.
        /// </summary>
        public static string rivendos2FA {
            get {
                return ResourceManager.GetString("rivendos2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivendos kodet.
        /// </summary>
        public static string rivendosKodet {
            get {
                return ResourceManager.GetString("rivendosKodet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruaj.
        /// </summary>
        public static string ruaj {
            get {
                return ResourceManager.GetString("ruaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendosni këto kode në një vend të sigurtë..
        /// </summary>
        public static string safeRecoveryCodes {
            get {
                return ResourceManager.GetString("safeRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shfletuesi aktual është fshirë. Kur të kyqeni nga ky shfletues do të kërkohen kodet 2FA..
        /// </summary>
        public static string shfletuesiFshire {
            get {
                return ResourceManager.GetString("shfletuesiFshire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkarko një aplikacion për autentifikim dy hapësh sikurse Microsoft Authenticator për.
        /// </summary>
        public static string shkarkoniAplikacioniPer2FA {
            get {
                return ResourceManager.GetString("shkarkoniAplikacioniPer2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shpenzimet mujore për paga.
        /// </summary>
        public static string shpenzimetPaga {
            get {
                return ResourceManager.GetString("shpenzimetPaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shteti.
        /// </summary>
        public static string shteti {
            get {
                return ResourceManager.GetString("shteti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto aplikacion për autentifikim.
        /// </summary>
        public static string shtoAplikacionin2FA {
            get {
                return ResourceManager.GetString("shtoAplikacionin2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasi të keni skanuar QR kodin or të keni shtypur çelësin e dhënë më sipër, aplikacionin juaj për autentifikim dy-hapësh do të gjeneroj një çelës unik për ju. Vendoseni këtë çelës në fushën e mëposhtme..
        /// </summary>
        public static string skanimiQRKodeveMeApp {
            get {
                return ResourceManager.GetString("skanimiQRKodeveMeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skano QR kodin ose shtype këtë çelës.
        /// </summary>
        public static string skanoQRKode {
            get {
                return ResourceManager.GetString("skanoQRKode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dita fillimit të pushimit.
        /// </summary>
        public static string startDateLeave {
            get {
                return ResourceManager.GetString("startDateLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusi.
        /// </summary>
        public static string statusi {
            get {
                return ResourceManager.GetString("statusi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatimi.
        /// </summary>
        public static string tatimi {
            get {
                return ResourceManager.GetString("tatimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA është deaktivizuar. You mund të vendosni përsëri 2FA pasi ta konfiguroni aplikacionin për autentifikim..
        /// </summary>
        public static string TOTPDeaktivizuar {
            get {
                return ResourceManager.GetString("TOTPDeaktivizuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentifikimi dy hapësh.
        /// </summary>
        public static string twoStepAuthenticationTitle {
            get {
                return ResourceManager.GetString("twoStepAuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekziston përdorues i regjistruar me këtë email adresë..
        /// </summary>
        public static string userExist {
            get {
                return ResourceManager.GetString("userExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri perdoruesit.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendos fjalëkalimin.
        /// </summary>
        public static string vendosFjalekalimin {
            get {
                return ResourceManager.GetString("vendosFjalekalimin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendos fjalëkalimin tuaj.
        /// </summary>
        public static string vendosFjalekaliminTuaj {
            get {
                return ResourceManager.GetString("vendosFjalekaliminTuaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veprimet.
        /// </summary>
        public static string veprimet {
            get {
                return ResourceManager.GetString("veprimet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ky veprim do të anuloj 2FA..
        /// </summary>
        public static string veprimTOTP {
            get {
                return ResourceManager.GetString("veprimTOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifiko.
        /// </summary>
        public static string verifiko {
            get {
                return ResourceManager.GetString("verifiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju patjeter duhet.
        /// </summary>
        public static string youMust {
            get {
                return ResourceManager.GetString("youMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjedhe.
        /// </summary>
        public static string zgjedhe {
            get {
                return ResourceManager.GetString("zgjedhe", resourceCulture);
            }
        }
    }
}
